# Generated by Django 2.2 on 2019-11-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0002_auto_20191104_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('details', models.TextField()),
                ('qual', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BP',
        ),
    ]
