# Generated by Django 2.2 on 2019-11-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0010_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pwd',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
    ]
