# Generated by Django 2.2 on 2019-11-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0015_auto_20191109_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='title',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
