# Generated by Django 2.2 on 2019-11-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0016_filemodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
